language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - public
    - ~/.cache
    - ~/.npm

env:
  global:
    - secure: 'OxsmzOrVfUkKAQPsSty3elzIjIyY7ycXK3drbxUcpO9phZNcFXnmylMiyp/hkJZ2znES/lieIik54O+A86xgTEZDfq/gPshi8YgR/s20l+89seuulXkjGOAui060RJt+Ipf7UNj6OQAM457K0ligT8kPhn6BEWq8s+Si6Qx5Jm6CVu6H/G7kCSzXz8nlhvApFUUImCsKRFp8czpl+CKDxMcgiGwykvFjHcQdiZXN2LPC+Lb62qVjn9qUA+svg/sb9wjnlcA9dou7KXIC3Syy/QnbRC/+3FAIcG01OlLQ7k2MF3Zi6Ko7kqyzMOtZzAMzbx95gvwFd8u2J1F2T+9SqXAFrjgV2HSnSMgZc5rNslsVtGa4Dx4fEscE638ntT79N7sj4MFrSuK6hXlR4ccCXw+rX0conOKYVykiIxanNJyJh7RxKwSRgqs8jb16Tsgm9kdZMmAejvmjHEg3dk/wrS09GmWT6ePTUYpJJRJjTMGRt4sMbcK0eAmmDs1Dm7Amwfp2syndV1k3f3ZbDZT0URnSQsVVQPihjqwHSnXA8wfMk8ChE3Bq4LkbBO0lot4x1o2IBGU9hMkZSWaCWRfLexdfOoegezsqhpf2EsAoB9NXiAqBddMl8AtHg9b8s8KjXGVn81Yr/l0F0eSE20YHB6A4Gb4G9F4nCr4NPGCDTqM='
    - CONTENTFUL_ENVIRONMENT: master
    - secure: 'T3+JVKi0aq8h0fmGuCQ944Qs5Z39SjAylSFLkK0XSBIpbPqon3WRV3du78J7C3GKhKjGNhuEce9JIMDwFo4fxPSug8znppXt6g66/+OBwkcOXmdCqTZqZ5LGHzrorUhj4ol9EzOgj2TjebhcLKETHo6LOazr3bjAc9d2nccbTxTtLxUS+oAWDjhOwVZEUZ515uTJGdP0zDhrk5OiPwIn7Q27H+QQ+6jQKa/YwaxGFMU/Lqo9wefw5PHWSzbfDcvmFDtX2F5QxyU4H7ZXCLOOvzpxPz0PjennLWNssUx9B32leVQh575/XGoCjTjSROoJkJX51VS2Lh293nzkvRD9vlWcmj4G9hqA5Ci1lL4MZ71H0JcKUqRX2IMFfR1wwYnXabxQErVSQZ/8vxCeC4GuZr+ktdFV0aJEQIhdQifoDrC0u3KswenewpgRS+c9L/PzzjlFFtIpjU1b1b6ehYPWYQ7qZUaP3yCHXNpLXv2riHs7/tV3LV0h0GMLKfp3HbIw2/gSC0fHBBBZ2b7YHdlJ40dU6jFvXdoBm9+qioFtpuPSeLYdmWcS58B1Dw7BVxmYsymunEsaQfWymb4J2viTXJV7Vosc1Gc2JHdsRc6iYJ3ESqvbMDmxEHQnIGcTtfe5XF516jzccp8ISPeiqlBVjGNwe2yagc5OZDdbt7R5FKg='
    - secure: 'TKA871IS4a2xQjyJlwUXHY4MB5nIwyKUtSi+gOevKt3s8CaFuzE4Hzlpljq2B91I5KXvlr3bzo7JXyIgKyK9qDkyKQsm2TtjJZlmgiEnMSn6Spo55qiO84QFIeqRCuMgm7+FruXzLGlxh6CFRqfgEx/mIDzwF1RXGfn3Nw764HRCQocVjwFo+9pt7/5EV3ySyn2gNe0vtuWJ4vZ5+fztMebr+FuSty8Bt69ATgaJHKvnv8orj2JHkuxknIMAHSUuf6Rqp3BdtAXqbSdno0IDYVLaxTYz5IYERSCKvrbFxHFlUh9DZSIUExOvKWeJCAOmHHynpSaCpDjU1WD8sC16v2H2AjjIYAVL5GNtKOKjSg5yAoJZEB4FVqCRpCJk0AXA7x/aNNtUgb2kV1GYTzKhVoCip4iwRhqqQ0NK5I+sc9UDMHyYYUpJw3skC4WBKnIhL27RmDOxEU6JStqiy0PWUm+YCbf42B4Eb0qubcJbUUTY0rE+V35mV2wq1A+iCQz2kTLeqgySnApZmz0Twa6QllZRTayEnORnr9mCdQO8cJ2KlSJUbhULN7bziOA3zhKKk1F/l38Cnh18tKzOWIbAiiNxbzoqPb3T9OIGvn9roIliar4zEK4KCmABgaYLaZ3CroeBOVKi1lTQUaeKzxbp+dxKTuNB0npKVmsAbu4F5vU='

install: npm ci

script: npm test

deploy:
  - provider: script
    script: npm run deploy:travis
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
