
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=production

install: yarn --dev
