language: node_js

cache:
  npm: true
  directories:
    - ~/.cache

env:
  global:
    - secure: 'OxsmzOrVfUkKAQPsSty3elzIjIyY7ycXK3drbxUcpO9phZNcFXnmylMiyp/hkJZ2znES/lieIik54O+A86xgTEZDfq/gPshi8YgR/s20l+89seuulXkjGOAui060RJt+Ipf7UNj6OQAM457K0ligT8kPhn6BEWq8s+Si6Qx5Jm6CVu6H/G7kCSzXz8nlhvApFUUImCsKRFp8czpl+CKDxMcgiGwykvFjHcQdiZXN2LPC+Lb62qVjn9qUA+svg/sb9wjnlcA9dou7KXIC3Syy/QnbRC/+3FAIcG01OlLQ7k2MF3Zi6Ko7kqyzMOtZzAMzbx95gvwFd8u2J1F2T+9SqXAFrjgV2HSnSMgZc5rNslsVtGa4Dx4fEscE638ntT79N7sj4MFrSuK6hXlR4ccCXw+rX0conOKYVykiIxanNJyJh7RxKwSRgqs8jb16Tsgm9kdZMmAejvmjHEg3dk/wrS09GmWT6ePTUYpJJRJjTMGRt4sMbcK0eAmmDs1Dm7Amwfp2syndV1k3f3ZbDZT0URnSQsVVQPihjqwHSnXA8wfMk8ChE3Bq4LkbBO0lot4x1o2IBGU9hMkZSWaCWRfLexdfOoegezsqhpf2EsAoB9NXiAqBddMl8AtHg9b8s8KjXGVn81Yr/l0F0eSE20YHB6A4Gb4G9F4nCr4NPGCDTqM='
    - secure: 'OX0Ao97BTVZWcEn2wRwo5BVRkStbXUVA0UGJMKuKqr34w1JzAM40nB/R0IK7JAdV6950oQc06me/3FnuKxwRTglQhpyOmQQ2MypELZdnW0CydFrzzfSZqhv3nVgABSrssjo+MTXmPYGnH1KY5SXGkploW+m1RIz1wOWUwU/UxiFxotWKifCr1jf7T/8T8QjmqzyFMyyfBP70Kn0uhbn9ZrHWIvyZ+Cnkgajlw5cMpB6rlpiJ6OkGeHcjZRwCY9ZXHGfoHly6399ri0oXsLFGTcWBfnd+xL6r9znk+1XBNGKRwNlHSyeAp+CSzRAYPXeRBn9S4FDB9SfoIu/DY/neNXRfkaDljHBwDIeD37NDYyF3DFiV3z83vJC6p6DRv1jY6C7gUF62I9OgIdRHVBp/j1E22KVVzj8lMvcFqK77V3Rm8xnLGvvX3flXZPTZePFHD4OH54EVm/NpIcGEunXokNUDcV2OPiYmiTFWo0xWQSH/JT2kwhK7+ZuBmx8AHvWtstQo6tGGtYAMYMjRYtmL+WQrdyK39znuHF3lG4tOzRU132SQHSIoLfYXilPx/Wt+wmPf8qoXY8oUGxVnK86on9QAHeD4MRLrBoCyu3elyqvwWhpdxSAG4M8VuVnWZBHsdk4FXzgc7uOqU4ks2XN4WYPNbnV6z4yMDKolHtFBJe4='
    - secure: 'Wr4oK38P32nhoRm/lWRieIS3ELuHqDVnB4D8Q4vmYnlGP2ffMaZGG/pzLRWpJjN3eECJikodl6oL0/7y3PA/gzjctUb6y3E+Q/GKMxw6GOPHRBi4aQd3IW/yrIfoxGsnvJWglco1Udap/m+oWZ3fppY/73ltvQE/VU7P/C5wfeqTq4fjE1wguseTNSAizH10f9aAsRR3vq77PipxAWFDkX3wAgB4cDuiQu26SO3dOmPrEtk6bVGoirBZ/0gCSPMvIpVOAxU5UV2YscIK36TORWU6PXKG6dFjJ28Hk3uszvr8y8S/QeEe38niZApwvKMVOzXgDTAxPqy67qXzjyzXxSoI9w27BrFDhHG6hwFFAiVI7ZzdKw/UG/XuCpFc5OKrj/toXFtws55ZRdxXiymyTpl6ZnlgARcZccdzslJ4+MrzmN18tnG81ek1zQ3T0NlGeAVuWN9zzTXJZ9DCvXn8cPgEoFI6N8TABS6aD77U5UHldtwLtqf09/PzMXc47og24/dprtUqnn0HEJ9IwNMG8CG9o2/Ig0FT3ZPm6IY9Iwkryy6m4qRkfSN6HEu2K20npa2fXGlQplHUT7g7Kgu6IaFonsjY1JvoHXWjgsLPfiqMhDBtPelOrzLHdJaLEjghM/MPqqRexNFPgqSs7llf9hrWeqXxDhpUMmuhSooGuTo='

branches:
  only:
    - master

install: npm ci

script: npm test && npm run build -- --prefix-paths

deploy:
  - provider: script
    script: curl -X POST -d {} https://api.netlify.com/build_hooks/$BUILD_HOOK_ID > /dev/null
    on:
      branch: master
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
