
language: node_js

cache:
    directories:
        - node_modules

env:
    global:
        - NODE_ENV=production
        - secure: neHOwTkrr6Pz0574O5ynfVsskNOiBrMaLcgkgYgI64sqgG+je3cPXa8cA0+IrB1hu3B48wOtUxXo2StRooAd6cy2l/TxdKOK5O9xoc//rzamuUYvFkdXt6Sf00fK6rnIJ3k2W9aalUb2/p+guvMTPkdAPjat8NiTF4CDeKZIuz45Yj/8TW8auvDWce0AASnN4TB4a+ZDwzUYHAPrByq4XIgVKB7BFDF2dLDltL1qaC5ka+9KGnLsJRUSj911jHEDRwfIN+aYQgSjzR5NW263FpZxD3Aqk48LerJtaIb+kjjEs5w8VtNEvkJcEokZIWU11oRnePJCS7WplGu+cSpOm09rqySaplpdb0KmWv1YbJQ0MGeZygZIi99RW1i7fxvB8UH+DidpO6Yz/9oG5y44zrcyhuGLwzZ59mn7SuJm6Bf+31kyEgGO+zZ8cRBaQxHiMPn1c9aJ9CnnpEjVZv3TFauICClCTfHl7UB5k02IamOS6fNDYSgsehTlh3WMUtqy2fRyD9okTOICV7RURFxQssQ905MrqJOqSi5fpi6+is+GrnBoQvv7zuhu2Q2dG/CBv1fwEbLFgYnKmY07UKN9Lh3zvxscLet6qqORoZBVO6Zmo+zeerd04aOjlxgNjLrW5WOCZ21qIAx/z4gtCdPPg1fYVx3u23/5EVZcGOnY0FA=
        - secure: L7EUduobu4oWrwwMnLln7sLu/BP/yzqkP+HMJxHVPPjZ/PcGYiqZT3XWAvAPcOzLRN0BuxgXP4XFfDw2nm0CK5uqDq2MIWB5JkbnXEXfpu1PmOOInMKQrCN2g8mJDzg9Ws4KT2gZ9VVrG/JyujWzMwCFfaOdQXEGa3F48bytNxVGvK+bg5YY5iafDkawJWgXWTLF4Qc89mW02Jd/gVoqL4twyGhsyvTfs57D1/34w216dRGkSbILndrX+13CEghMVMkbIKMcoY+yOxE8PSP9GCqFHu97r4I7Y7gzhL6yuePnixTnHpWBm0bu6VCkQzCud3aBt791oHAHoFdnQ6sC5LiRl7WaU3UeAVAFXKnYK++9nl5ilGo2TWZBTA/CjeEbZWTh5nPiDlYXL9kaWLjQHVIww+ogWDKCggXc7HdD9qvqlqZtwdzbvUrbFuZFU3sUSTwjdEhG9XSacKaGFYtbWkIkOtMOG3h/4aU8QbGCRA0jATdoOjQNGLHefXkoPmCNO8fF2FbwRTfhVofuNzAfAsk/8ytk8lHwiQhuLyo6yBRGPRq13mxZTcLDcjd5OMNXNn2n887Nnd3y32iZnnS0HnZ1GbkKwepgg9MIag/PCl5QW8SZFM767mjBaecYkhR712dbzZ0pLx3JLhhsNkKddNSDJVorE46bzMCusP80xnw=

deploy:
    provider: script
    script: ./script/deploy
    skip_cleanup: true
    on:
        branch:
            - master
