language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - public
    - ~/.cache
    - ~/.npm

env:
  global:
    - secure: 'OxsmzOrVfUkKAQPsSty3elzIjIyY7ycXK3drbxUcpO9phZNcFXnmylMiyp/hkJZ2znES/lieIik54O+A86xgTEZDfq/gPshi8YgR/s20l+89seuulXkjGOAui060RJt+Ipf7UNj6OQAM457K0ligT8kPhn6BEWq8s+Si6Qx5Jm6CVu6H/G7kCSzXz8nlhvApFUUImCsKRFp8czpl+CKDxMcgiGwykvFjHcQdiZXN2LPC+Lb62qVjn9qUA+svg/sb9wjnlcA9dou7KXIC3Syy/QnbRC/+3FAIcG01OlLQ7k2MF3Zi6Ko7kqyzMOtZzAMzbx95gvwFd8u2J1F2T+9SqXAFrjgV2HSnSMgZc5rNslsVtGa4Dx4fEscE638ntT79N7sj4MFrSuK6hXlR4ccCXw+rX0conOKYVykiIxanNJyJh7RxKwSRgqs8jb16Tsgm9kdZMmAejvmjHEg3dk/wrS09GmWT6ePTUYpJJRJjTMGRt4sMbcK0eAmmDs1Dm7Amwfp2syndV1k3f3ZbDZT0URnSQsVVQPihjqwHSnXA8wfMk8ChE3Bq4LkbBO0lot4x1o2IBGU9hMkZSWaCWRfLexdfOoegezsqhpf2EsAoB9NXiAqBddMl8AtHg9b8s8KjXGVn81Yr/l0F0eSE20YHB6A4Gb4G9F4nCr4NPGCDTqM='

install: npm ci

script: npm test

deploy:
  - provider: script
    script: npm run deploy:travis
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
