name: Build and Test and Deploy

on:
  push:
    branches:
      - KillYourMaster
  pull_request:
  repository_dispatch:
    types: deploy

env:
  GATSBY_TELEMETRY_DISABLED: 1
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
  CONTENTFUL_ENVIRONMENT: master
  BUILD_HOOK_ID: ${{ secrets.BUILD_HOOK_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the branch
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache public dir
        uses: actions/cache@v2
        with:
          path: ./public
          key: ${{ runner.os }}-public-${{ hashFiles('_*/**/*', 'src/**/*', 'static/**/*') }}
          restore-keys: ${{ runner.os }}-public-

      - name: Cache .cache dir
        uses: actions/cache@v2
        with:
          path: ./.cache
          key: ${{ runner.os }}-dot-cache-${{ hashFiles('_sets/**/*.jpg') }}
          restore-keys: ${{ runner.os }}-dot-cache-

      - name: Test the site
        run: |
          npm ci
          npm test

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: failure-screenshots
          path: screenshot-*.png

      - name: Build the site
        run: npm run predeploy
        env:
          IMG_QUALITY: 75
          PREVIEW_ID: ${{ github.ref != 'refs/heads/KillYourMaster' && github.sha || '' }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        if: ${{ success() }}
        with:
          publish-dir: './public'
          production-branch: KillYourMaster
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from herschel666/photoblog'
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: ${{ github.sha }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
