name: Build and Test and Deploy

on: [push, pull_request]

env:
  GATSBY_TELEMETRY_DISABLED: 1
  CONTENTFUL_ENVIRONMENT: master
  BUILD_HOOK_ID: ${{ secrets.BUILD_HOOK_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build & test the application
        run: |
          npm ci
          npm test

      - name: Deploy the application
        if: github.ref == 'refs/heads/master'
        run: npm run deploy
