name: Build and Test and Deploy

on:
  push:
  pull_request:
  repository_dispatch:
    types: deploy

env:
  GATSBY_TELEMETRY_DISABLED: 1
  CONTENTFUL_ENVIRONMENT: master
  BUILD_HOOK_ID: ${{ secrets.BUILD_HOOK_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the branch
        uses: actions/checkout@v1
        with:
          lfs: true

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache public dir
        uses: actions/cache@v2
        with:
          path: ./public
          key: ${{ runner.os }}-public-${{ hashFiles('_*/**/*', 'src/**/*', 'static/**/*') }}
          restore-keys: ${{ runner.os }}-public-

      - name: Cache .cache dir
        uses: actions/cache@v2
        with:
          path: ./.cache
          key: ${{ runner.os }}-dot-cache-${{ hashFiles('_sets/**/*.jpg') }}
          restore-keys: ${{ runner.os }}-dot-cache-

      - name: Build & test the application
        run: |
          npm ci
          npm test

      - name: Deploy the application
        if: github.ref == 'refs/heads/KillYourMaster'
        run: npm run deploy
